services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-processor
    environment:
      - MONGO_URI=mongodb://mongodb:27017/images
      - DEFAULT_BATCH_SIZE=10
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    depends_on:
      - mongodb
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
    command: ['node', '--expose-gc', 'index.js']

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=images
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
